### ISSUE TITLE
Error running "npm test"

### ISSUE THREAD

**Issue by leibovic** [mozilla-services/switchboard-server#6]
I tried updating the EXPERIMENTS_FILE environment variable, but that didn't fix my error:

```
[leibovic@margaret-mbp:~/code/switchboard-server]$ npm test

> switchboard-server@0.0.1 test /Users/leibovic/code/switchboard-server
> EXPERIMENTS_FILE=config/basic_experiments.json mocha --compilers js:mocha-babel test/*.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'mocha-babel'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/leibovic/code/switchboard-server/node_modules/mocha/bin/_mocha:296:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/leibovic/code/switchboard-server/node_modules/mocha/bin/_mocha:290:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

> npm ERR! Test failed.  See above for more details.

**Comment by milescrabill** [comment]
Whoops, this was my fault - I moved the base experiments file and didn't change the `npm test` command. Fixed in 8c436d5f8aa5ce7e473455d659076b0381ad18de.

**Comment by leibovic** [comment]
@milescrabill With that change, this still doesn't fix the error I'm seeing trying to run `npm test`. I did run `npm install` first. Is there something else I need to do to set up the test environment?

```
[leibovic@margaret-mbp:~/code/switchboard-server]$ npm test

> switchboard-server@0.0.1 test /Users/leibovic/code/switchboard-server
> EXPERIMENTS_FILE=test/test_config.json mocha --compilers js:mocha-babel test/*.js

module.js:338
    throw err;
    ^

Error: Cannot find module 'mocha-babel'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/leibovic/code/switchboard-server/node_modules/mocha/bin/_mocha:302:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/leibovic/code/switchboard-server/node_modules/mocha/bin/_mocha:296:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
npm ERR! Test failed.  See above for more details
```

**Comment by milescrabill** [comment]
Ah! Whoops, the error was twofold and I only addressed one half! You have to `npm install --dev` to get the dev dependencies per the `package.json`. After that it should work. You shouldn't have to install them globally, but it just looks like you don't have `mocha-babel` installed.

**Comment by leibovic** [comment]
@milescrabill It looks like mocha-babel isn't supported anymore: 
https://www.npmjs.com/package/mocha-babel

What are you using it for? Can we replace that with something else?

**Comment by milescrabill** [comment]
Fixed not to rely on mocha-babel in bcbac1d.
